<?php
// $Id$
 
/**
 * @file
 * Drupal Module: mysite
 * Adds custom code specific to this Drupal 6 site.
 */
 
/**
 * Implementation of hook_form_alter().
 */
function jacek_form_alter(&$form, &$form_state, $form_id) {
  print $form_id;
  switch ($form_id) {
    case 'blog_node_form':
      // remove some unwanted node editing fields
      $form['revision_information']['#access'] = 0;
      $form['menu']['#access'] = 0;
      $form['author']['#access'] = 0;
      // override node options permissions defined by 'administer nodes'
      $form['options']['#access'] = 1;
      $form['options']['status']['#access'] = 1;
      $form['options']['promote']['#access'] = 0;
      $form['options']['sticky']['#access'] = 0;
    break;
    case 'page_node_form':
      // don't ever allow page nodes to be promoted or sticky
      $form['options']['promote']['#access'] = 0;
      $form['options']['sticky']['#access'] = 0;
    break;
  }
}