<?php

/**
 * @file
 *   block2form converts any forms or node into block
 *
 * @version
 *
 * @developers:
 *    Rafal Wieczorek <kenorb@gmail.com>
 */

/**
 * Implementation of hook_menu().
 */
function block2form_menu() { 
  if (!module_exists('drupal_tweaks')) {
    $items['admin/settings/block2form'] = array(
      'title' => 'Database Tweaks',
      'description' => t('Convert any form or node into block.'),
      'page callback' => 'drupal_get_form', 
      'page arguments' => array('form2block_settings_form'), 
      'access arguments' => array('administer block2form'),
      'file' => 'form2block.admin.inc', 
    );
  }

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function block2form_perm() {
   return array('administer block2form');
}

/**
 * Implementation of hook_block().
 *
 */
function block2form_block($op = 'list', $delta = 0, $edit = array()) {
  // The $op parameter determines what piece of information is being requested.
/*
  switch ($op) {
    case 'list':
      // If $op is "list", we just need to return a list of block descriptions.
      // This is used to provide a list of possible blocks to the administrator,
      // end users will not see these descriptions.
      // You can override default settings: 'weight'     => 0, //'pages'      => 'node/*',
      $blocks['block2form_tester'] = array(
        'info'       => t('block2form Tester'),
      );
      $blocks['block2form_live_options'] = array(
        'info'       => t('block2form Options'),
      );
      $blocks['block2form_quick_reference'] = array(
        'info'       => t('JavaScript Regex Quick Reference'),
      );
      return $blocks;
    case 'view': default:
      module_load_include('form.inc', 'block2form');
      switch ($delta) {
        case 'block2form_tester':
          $block['subject'] = t('block2form Tester');
          $block['content'] = drupal_get_form('block2form_tester_form');
          $block['region'] = 'content';
          $block['visibility'] = 1; // 1 = Show on only the listed pages.
          $block['pages'] = 'admin/settings/personalized_settings';
          $block['weight'] = 0;
          break;
        case 'block2form_live_options':
          $block['subject'] = t('block2form Options');
          $block['content'] = drupal_get_form('block2form_live_options_form');
          break;
        case 'block2form_quick_reference':
          $block['subject'] = t('JavaScript Regex Quick Reference');
          $block['content'] = theme('block2form_quick_reference');
          $block['region'] = 'right';
          $block['visibility'] = 1; // 1 = Show on only the listed pages.
          $block['pages'] = 'admin/settings/personalized_settings';
          $block['weight'] = 1;
          break;
      }
      return $block;
  }
*/
}

