<?php

include_once('housemedia_core.features.inc');

function _housemedia_core_translations() {
  t('Document');
}

/**
 * Implementation of hook_block().
 */
function housemedia_core_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    return array(
    	'search'     => array('info' => t('Search (quicktabs)')),
      'ranks'      => array('info' => t('Ranks (quicktabs')),
    );
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 'search':
        return housemedia_core_search_block();
        break;
      case 'ranks':
        return housemedia_core_ranks_block();
        break;
    }
  }
}

function housemedia_core_search_block() {
  
  $quicktabs['qtid']  = 'housemedia_core_search';
  $quicktabs['ajax']  = FALSE;
  $quicktabs['style'] = 'nostyle';
  $quicktabs['tabs']  = array(
    '0' => array(
  		'title'   => t('Investments'),
      'type'    => 'view',
      'vid'     => 'og_inwestycje',
      'display' => 'block_1',
    ),
    '1' => array(
  		'title'   => t('Flat'),
      'type'    => 'view',
      'vid'     => '',
      'display' => '',
    ),
    '2' => array(
  		'title'   => t('Others'),
      'type'    => 'view',
      'vid'     => '',
      'display' => '',
    )
  );

  
  return array(
    'subject' => t('Search'),
    'content' => theme('quicktabs', $quicktabs)
  );
}

function housemedia_core_ranks_block() {
  
  $quicktabs['qtid']  = 'hm_core_ranks';
  $quicktabs['ajax']  = FALSE;
  $quicktabs['style'] = 'nostyle';
  $quicktabs['tabs']  = array(
    '0' => array(
  		'title'   => t('Investments'),
      'type'    => 'view',
      'vid'     => 'hm_group_ranks',
      'display' => 'block_1',
    ),
    '1' => array(
  		'title'   => t('Advisers'),
      'type'    => 'view',
      'vid'     => '',
      'display' => '',
    ),
  );

  
  return array(
    'subject' => t('Ranks'),
    'content' => theme('quicktabs', $quicktabs)
  );
}

